import * as fs from 'fs';
import * as path from 'path';
import { VideoAnalysisResult } from '../analyzer/types';

export class CodeGenerator {
    private clonesDir: string;
    private registryPath: string;

    constructor(remotionSrcDir: string) {
        this.clonesDir = path.join(remotionSrcDir, 'clones');
        this.registryPath = path.join(this.clonesDir, 'registry.ts');

        if (!fs.existsSync(this.clonesDir)) {
            fs.mkdirSync(this.clonesDir, { recursive: true });
        }
    }

    generateComposition(videoName: string, analysis: VideoAnalysisResult) {
        const componentName = this.sanitizeComponentName(videoName);
        const componentDir = path.join(this.clonesDir, componentName);

        if (!fs.existsSync(componentDir)) {
            fs.mkdirSync(componentDir, { recursive: true });
        }

        // 1. Create Composition.tsx
        const compositionContent = `
import { AbsoluteFill, useCurrentFrame, interpolate, Audio } from 'remotion';
import React from 'react';
import { z } from 'zod';
import { Prompt } from './Prompt';

// Schema for dynamic props
export const ${componentName}Schema = z.object({
  title: z.string(),
});

export const ${componentName}: React.FC<z.infer<typeof ${componentName}Schema>> = ({ title }) => {
  const frame = useCurrentFrame();
  const videoName = "${videoName}";
  const publicPath = \`/clones/\${videoName}/\`;
  
  // This is a placeholder component generated by DreamCrafter7.
  // Use the Prompt below (and the assets in public/clones/${videoName}) to ask an AI to write the real code!
  
  return (
    <AbsoluteFill style={{ backgroundColor: 'black' }}>
      <Prompt />
      <div style={{
          position: 'absolute', 
          top: 20, 
          left: 20, 
          color: 'white',
          fontFamily: 'monospace'
      }}>
        <h1>DreamCrafter7 Clone: ${videoName}</h1>
        <p>Frame: {frame}</p>
        <p>Assets Path: {publicPath}</p>
      </div>
    </AbsoluteFill>
  );
};
`;
        fs.writeFileSync(path.join(componentDir, 'Composition.tsx'), compositionContent);

        // 2. Create Prompt.tsx (To display the AI prompt in the preview)
        const promptContent = `
import { AbsoluteFill } from 'remotion';
import React from 'react';

const promptText = \`${analysis.generatedPrompt?.replace(/`/g, '\\`')}\`;

export const Prompt: React.FC = () => {
  return (
    <div style={{
        zIndex: 1000,
        backgroundColor: 'rgba(0,0,0,0.8)',
        color: '#00ff00',
        padding: 40,
        fontFamily: 'monospace',
        whiteSpace: 'pre-wrap',
        fontSize: 14,
        overflow: 'auto',
        height: '100%'
    }}>
        <h2>🤖 AI Replication Prompt</h2>
        <hr style={{borderColor: '#333'}}/>
        {promptText}
    </div>
  );
};
`;
        fs.writeFileSync(path.join(componentDir, 'Prompt.tsx'), promptContent);

        // 3. Update Registry
        this.updateRegistry(componentName, analysis);
    }

    private sanitizeComponentName(name: string): string {
        // Convert "travel77" to "Travel77"
        // Remove non-alphanumeric, camel case
        return name.charAt(0).toUpperCase() + name.slice(1).replace(/[^a-zA-Z0-9]/g, '');
    }

    private updateRegistry(componentName: string, analysis: VideoAnalysisResult) {
        // We need to append the new composition to registry.ts
        // This is a bit hacky (parsing TS file as string), but efficient for this purpose.

        let registryContent = fs.readFileSync(this.registryPath, 'utf-8');

        // Check if already registered
        if (registryContent.includes(componentName)) {
            console.log(`[CodeGenerator] ${componentName} already registered.`);
            return;
        }

        // Add import
        const importStatement = `import { ${componentName} } from './${componentName}/Composition';\n`;
        if (!registryContent.includes(importStatement)) {
            registryContent = importStatement + registryContent;
        }

        // Add entry to array
        const newEntry = `
    {
        id: '${componentName}',
        component: ${componentName},
        durationInFrames: ${Math.round(analysis.metadata.duration * analysis.metadata.fps)},
        fps: ${Math.round(analysis.metadata.fps)},
        width: ${analysis.metadata.width},
        height: ${analysis.metadata.height},
        defaultProps: {
            title: '${componentName}'
        }
    },`;

        // Insert before the closing bracket of the array
        const arrayEndIndex = registryContent.lastIndexOf('];');
        if (arrayEndIndex !== -1) {
            registryContent = registryContent.slice(0, arrayEndIndex) + newEntry + registryContent.slice(arrayEndIndex);
        }

        fs.writeFileSync(this.registryPath, registryContent);
        console.log(`[CodeGenerator] Registered ${componentName} in Remotion Root.`);
    }
}
